adding navigation buttons - closes #17
mozilla/web-lit-core pull request #18
Opened 2018-03-19 21:49 UTC by gvn

2018-03-20 17:57 UTC, gvn commented
@ScottDowne can you review this?

2018-03-20 19:20 UTC, ScottDowne commented on _layouts/default.html
> +            {% if page.previous.url and page.next.url %}
Shouldn't this be an "or" and not an "and"?

2018-03-20 19:21 UTC, ScottDowne commented on css/main.css
> +  .next-prev .wrapper {
Just some whitespace that could be cleaned up it looks like.

2018-03-20 19:21 UTC, ScottDowne requested changes
Left two comments.

2018-03-21 14:16 UTC, ScottDowne approved these changes
Looks good!

2018-03-22 16:57 UTC, merged